repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        types_or:
          - python
          - pyi
          - jupyter
        always_run: true
        entry: uv run --frozen ruff format --force-exclude
        language: system
        require_serial: true
