import { TestData } from './types';

export const mockTestData: TestData[] = [
        {
          test_type_method: "NZS 4402:1986 Test 4.1.1",
          test_type_name: "Dry density/water content relationship (standard compaction) multiple points",
          display_name: "NZS 4402 MDD-Std(multi)",
          ags_code: "CMPG|CMPT",
          adit_id: "A0850",
          location_id: "TP5045",
          depth_to: 1.0,
          sample_reference: "TP5045_TP_BUCKET_0",
          sample_type: "Bucket",
          date_sampled: "29-10-2024",
          sample_unique_id: "1035",
          test_no: 1,
          shear_vane_method: "NZGS Hand Held",
          date_tested: "15-01-2025",
          date_checked: "20-01-2025",
          date_approved: "",
          natural_water_content: 38.5,
          optimum_dry_density: 1.553,
          bulk_density: 1.923,
          water_content: 24.0,
          solid_density: 2.603,
          air_voids: 0.6,
          shear_strength: 147,
          remark_dot_test_remarks: "Laboratory Description: Silty CLAY, with some silt and minor gravel; greyish brown. Very soft, moist, high plasticity.",
          mdd_results: [
            { test_no: 1, water_content: 31.63, dry_density: 1.413 },
            { test_no: 2, water_content: 27.87, dry_density: 1.499 },
            { test_no: 3, water_content: 23.67, dry_density: 1.548 },
            { test_no: 4, water_content: 19.66, dry_density: 1.479 },
            { test_no: 5, water_content: 15.58, dry_density: 1.46 },
            { test_no: 6, water_content: 0.0, dry_density: 0.0 },
            { test_no: 7, water_content: 0.0, dry_density: 0.0 },
          ],
        },
        {
          test_type_method: "NZS 4402:1986 Test 4.1.1",
          test_type_name: "Dry density/water content relationship (standard compaction) multiple points",
          display_name: "NZS 4402 MDD-Std(multi)",
          ags_code: "CMPG|CMPT",
          adit_id: "A0858",
          location_id: "TP5050",
          depth_to: 1.0,
          sample_reference: "TP5050_TP_BUCKET_0",
          sample_type: "Bucket",
          date_sampled: "01-11-2024",
          sample_unique_id: "1043",
          test_no: 1,
          shear_vane_method: "NZGS Hand Held",
          date_tested: "15-01-2025",
          date_checked: "20-01-2025",
          date_approved: "",
          natural_water_content: 26.8,
          optimum_dry_density: 1.653,
          bulk_density: 2.003,
          water_content: 21.0,
          solid_density: 2.753,
          air_voids: 4.8,
          shear_strength: 212,
          remark_dot_test_remarks: "Laboratory Description: Clayey SILT, with some sand and minor gravel; greyish brown. Firm, moist, high plasticity.",
          mdd_results: [
            { test_no: 1, water_content: 24.86, dry_density: 1.564 },
            { test_no: 2, water_content: 21.55, dry_density: 1.643 },
            { test_no: 3, water_content: 18.86, dry_density: 1.639 },
            { test_no: 4, water_content: 15.58, dry_density: 1.569 },
            { test_no: 5, water_content: 12.58, dry_density: 1.537 },
            { test_no: 6, water_content: 0.0, dry_density: 0.0 },
            { test_no: 7, water_content: 0.0, dry_density: 0.0 },
          ],
        },
        {
          test_type_method: "NZS 4402:1986 Test 4.1.1",
          test_type_name: "Dry density/water content relationship (standard compaction) multiple points",
          display_name: "NZS 4402 MDD-Std(multi)",
          ags_code: "CMPG|CMPT",
          adit_id: "A0866",
          location_id: "TP5081",
          depth_to: 3.5,
          sample_reference: "TP5081_TP_BUCKET_2.9",
          sample_type: "Bucket",
          date_sampled: "13-11-2024",
          sample_unique_id: "1051",
          test_no: 1,
          shear_vane_method: "Not Applicable",
          date_tested: "16-01-2025",
          date_checked: "26-02-2025",
          date_approved: "",
          natural_water_content: 33.4,
          optimum_dry_density: 1.703,
          bulk_density: 1.963,
          water_content: 17.0,
          solid_density: 2.603,
          air_voids: -0.1,
          shear_strength: null,
          remark_dot_test_remarks: "Laboratory Description: Silty SAND; brown. Soft, wet, dilatant.",
          mdd_results: [
            { test_no: 1, water_content: 30.81, dry_density: 1.439 },
            { test_no: 2, water_content: 25.97, dry_density: 1.554 },
            { test_no: 3, water_content: 21.26, dry_density: 1.661 },
            { test_no: 4, water_content: 16.31, dry_density: 1.694 },
            { test_no: 5, water_content: 11.41, dry_density: 1.622 },
            { test_no: 6, water_content: 0.0, dry_density: 0.0 },
            { test_no: 7, water_content: 0.0, dry_density: 0.0 },
          ],
        },
        {
          test_type_method: "NZS 4402:1986 Test 4.1.1",
          test_type_name: "Dry density/water content relationship (standard compaction) multiple points",
          display_name: "NZS 4402 MDD-Std(multi)",
          ags_code: "CMPG|CMPT",
          adit_id: "A0867",
          location_id: "TP5082",
          depth_to: 2.5,
          sample_reference: "TP5082_TP_BUCKET_1.7",
          sample_type: "Bucket",
          date_sampled: "14-11-2024",
          sample_unique_id: "1052",
          test_no: 1,
          shear_vane_method: "Not Applicable",
          date_tested: "16-01-2025",
          date_checked: "29-01-2025",
          date_approved: "",
          natural_water_content: 15.2,
          optimum_dry_density: 1.733,
          bulk_density: 1.973,
          water_content: 14.0,
          solid_density: 2.433,
          air_voids: 1.7,
          shear_strength: null,
          remark_dot_test_remarks: "Laboratory Description: SAND, with minor silt; greyish brown. Moist.",
          mdd_results: [
            { test_no: 1, water_content: 14.72, dry_density: 1.728 },
            { test_no: 2, water_content: 17.58, dry_density: 1.673 },
            { test_no: 3, water_content: 20.15, dry_density: 1.626 },
            { test_no: 4, water_content: 8.98, dry_density: 1.698 },
            { test_no: 5, water_content: 11.96, dry_density: 1.711 },
            { test_no: 6, water_content: 0.0, dry_density: 0.0 },
            { test_no: 7, water_content: 0.0, dry_density: 0.0 },
          ],
        },
      ];
      