import { SystemData } from './types';

export const mockSystemsData: SystemData[] = [
  {
    "BusinessArea": "00 - Commercial",
    "Category": "Estimating",
    "System": "Candy CCS",
    "Purpose": "Estimating",
    "Requirement": "9 - Unknown",
    "Phase": "0 - IPAA",
    "Licence": "Unknown",
    "SMEResponsible": "TBC",
    "ProjectRole": "Commercial Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "00 - Commercial",
    "Category": "Financial",
    "System": "My Hours",
    "Purpose": "Timesheet logging",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Dave Braendler",
    "ProjectRole": "Digital Lead",
    "Adoption": "5 - comprehensive",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "00 - Commercial",
    "Category": "Financial",
    "System": "Workbench & financial systems",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Evan Darwen",
    "ProjectRole": "IT Lead",
    "Adoption": "3 - good",
    "HostedBy": "MacDow"
  },
  {
    "BusinessArea": "00 - Commercial",
    "Category": "Financial",
    "System": "Sun Systems",
    "Purpose": "Accounting  system for Payment of Suppliers, Balance Sheet and P&L Creation",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "Evan Darwen",
    "ProjectRole": "nan",
    "Adoption": "8 - Not commenced",
    "HostedBy": "nan"
  },
  {
    "BusinessArea": "00 - Commercial",
    "Category": "Risk",
    "System": "Project Orbit",
    "Purpose": "PowerBI tracking (Risk Tracking plus others)",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Marcus Lin",
    "ProjectRole": "Risk Manager",
    "Adoption": "3 - good",
    "HostedBy": "T+T"
  },
  {
    "BusinessArea": "00 - Commercial",
    "Category": "Risk",
    "System": "Actve Risk Manager (ARM)",
    "Purpose": "Risk database",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - NZTA Provided",
    "SMEResponsible": "Marcus Lin",
    "ProjectRole": "Risk Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "NZTA"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "1 - Storage Location/Platform (CDE)",
    "System": "12D Synergy - (CDE design phase)",
    "Purpose": "File storage (CDE)",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "AJ Loader/Wendy Cairns",
    "ProjectRole": "IM Lead/DE Lead",
    "Adoption": "3 - good",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "1 - Storage Location/Platform (CDE)",
    "System": "ProjectWise (Open Roads/Open Bridge)",
    "Purpose": "OpenRoads - Roading and OpenBridge \u0096 Structures",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - Beca Provided",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "3 - good",
    "HostedBy": "Beca"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "1 - Storage Location/Platform (CDE)",
    "System": "Autodesk Construction Cloud  (ACC)",
    "Purpose": "Field data collection \u0096 quality assurance, quality control, internal audit",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - Beca Provided",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "2 - average",
    "HostedBy": "Beca"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "1 - Storage Location/Platform (CDE)",
    "System": "Seequent Central",
    "Purpose": "3D Modelling, Site Investigations",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "3 - good",
    "HostedBy": "T+T"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "2 - Production",
    "System": "Autocad",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "3 - good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "2 - Production",
    "System": "Open Roads",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "5 - comprehensive",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "2 - Production",
    "System": "Inventor",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Marcus Reiberg",
    "ProjectRole": "Temp Works/Construction",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "2 - Production",
    "System": "Revit",
    "Purpose": "nan",
    "Requirement": "2 - Could Have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke/Ted Polley",
    "ProjectRole": "CAD Lead/Structural Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "3 - Design Software",
    "System": "12D Model",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Wendy Cairns",
    "ProjectRole": "DE Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "3 - Design Software",
    "System": "Open Roads",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "3 - Design Software",
    "System": "Open Bridge",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "3 - Design Software",
    "System": "Civil 3D",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "7 - Unknown",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "3 - Design Software",
    "System": "Leap Frog",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "3 - Design Software",
    "System": "CSi Bridge",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "7 - Unknown",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "3 - Design Software",
    "System": "Space Grass",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "DE Lead",
    "Adoption": "7 - Unknown",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "4 - Clash detect/Federation",
    "System": "iTwin",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - Beca Provided",
    "SMEResponsible": "Matt Arcus",
    "ProjectRole": "Geeometrics Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "4 - Clash detect/Federation",
    "System": "BlueBeam",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "3 - good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "4 - Clash detect/Federation",
    "System": "Navisworks",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "5 - Visualization",
    "System": "LumenRT",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - Beca Provided",
    "SMEResponsible": "Craig Burke",
    "ProjectRole": "CAD Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "6 - Geotechnical",
    "System": "PLAXIS 2D",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "6 - Geotechnical",
    "System": "SLOPE/W",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "6 - Geotechnical",
    "System": "Slide2",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "6 - Geotechnical",
    "System": "WALLAP",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "6 - Geotechnical",
    "System": "Settle3",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "6 - Geotechnical",
    "System": "MSEW+",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "6 - Geotechnical",
    "System": "Infinity - Apeiron",
    "Purpose": "nan",
    "Requirement": "1 - Would Have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Emma Christie",
    "ProjectRole": "Geotech Lead",
    "Adoption": "4 - very good",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "7 - Traffic / Transport",
    "System": "SignCad",
    "Purpose": "nan",
    "Requirement": "1 - Would Have",
    "Phase": "0 - IPAA",
    "Licence": "Unknown",
    "SMEResponsible": "Ryan Dunn",
    "ProjectRole": "Traffic / Transport Lead",
    "Adoption": "3 - good",
    "HostedBy": "Unknown"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "7 - Traffic / Transport",
    "System": "SIDRA",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "Ryan Dunn",
    "ProjectRole": "Traffic / Transport Lead",
    "Adoption": "3 - good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "01 - Design",
    "Category": "7 - Traffic / Transport",
    "System": "Saturn",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Unknown",
    "SMEResponsible": "Ryan Dunn",
    "ProjectRole": "Traffic / Transport Lead",
    "Adoption": "3 - good",
    "HostedBy": "Beca"
  },
  {
    "BusinessArea": "02 - Engineering",
    "Category": "Information Management",
    "System": "CONQA",
    "Purpose": "Lots management, ITPs, snag lists, CWP, Handover packages, Issues etc.",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "AJ Loader",
    "ProjectRole": "Quality Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "02 - Engineering",
    "Category": "Survey",
    "System": "Survey Software - PAA",
    "Purpose": "Refer tab '4-Engineering'",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Jan",
    "ProjectRole": "Survey Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "02 - Engineering",
    "Category": "Survey",
    "System": "Survey Software - IPAA",
    "Purpose": "Refer tab '4-Engineering'",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Tim Swann",
    "ProjectRole": "Survey Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "02 - Engineering",
    "Category": "Survey",
    "System": "Survey Hardware",
    "Purpose": "Refer tab '4-Engineering'",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Jan",
    "ProjectRole": "Survey Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "03 - IT",
    "Category": "NZTA Provided",
    "System": "Sharepoint Hub, Infrastructure, Networking, Security, etc",
    "Purpose": "nan",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Zero Cost - NZTA Provided",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "3 - good",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "03 - IT",
    "Category": "Base IT Services",
    "System": "South - Sharepoint + Services",
    "Purpose": "Refer tab '3-IT'",
    "Requirement": "0 - Must have",
    "Phase": "2 - IPAA + PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "03 - IT",
    "Category": "Base IT Services",
    "System": "South - Internet + Security",
    "Purpose": "Refer tab '3-IT'",
    "Requirement": "0 - Must have",
    "Phase": "2 - IPAA + PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "03 - IT",
    "Category": "Base IT Services",
    "System": "South - Data Storage",
    "Purpose": "Refer tab '3-IT'",
    "Requirement": "0 - Must have",
    "Phase": "2 - IPAA + PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "03 - IT",
    "Category": "Base IT Services",
    "System": "South - BI/AI",
    "Purpose": "Refer tab '3-IT'",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "03 - IT",
    "Category": "Base IT Services",
    "System": "Copying",
    "Purpose": "Refer tab '3-IT'",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "03 - IT",
    "Category": "IT Hardware",
    "System": "Timescape cameras",
    "Purpose": "nan",
    "Requirement": "2 - Could Have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Main",
    "System": "Offices - Main - 100 desks (North Manakau Road)",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (1) - Type 1 - 15 desks - Kuku East Rd",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (2) - Type 1 - 15 desks - South Manakau  Rd",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (3) - Type 1 - 15 desks - Taylors Rd",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "9 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (4) - Type 2 -  8 people - Waikawa River North Borrow Pit",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "1 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "10 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (5) - Type 2 - 8 people - Manakau Heighgts Drive",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "2 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "11 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (6) - Type 2 -  8 people - PAT Underpass 1",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "3 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "12 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (7) - Type 2 - 8 people - PAT Underpass 2",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "4 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "13 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (8) - Type 3 - 4 people - Mobile office",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "5 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "14 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "04 - Fitout",
    "Category": "Offices - Site",
    "System": "Offices - Sites (9) - Type 3 - 4 people - Mobile office",
    "Purpose": "Refer tab '4-Fitout'",
    "Requirement": "6 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "15 - N/A",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "05 - Environmental",
    "Category": "Environmental",
    "System": "BraveGen",
    "Purpose": "platform for environmental compliance management.",
    "Requirement": "9 - Unknown",
    "Phase": "1- PAA",
    "Licence": "Unknown",
    "SMEResponsible": "Kate Searle",
    "ProjectRole": "Environmental Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "05 - Environmental",
    "Category": "Environmental",
    "System": "CSVUE",
    "Purpose": "Compliance software for environmental",
    "Requirement": "9 - Unknown",
    "Phase": "1- PAA",
    "Licence": "Zero Cost - NZTA Provided",
    "SMEResponsible": "Kate Searle",
    "ProjectRole": "Environmental Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "05 - Environmental",
    "Category": "Sustainability",
    "System": "Co Go",
    "Purpose": "Carbon Emision Tracking",
    "Requirement": "2 - Could Have",
    "Phase": "1- PAA",
    "Licence": "Unknown",
    "SMEResponsible": "Sam Turner",
    "ProjectRole": "Sustainability Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "06 - HSEQ",
    "Category": "HEALTH & SAFETY",
    "System": "CMO",
    "Purpose": "Compliance management system - HSEQ Forms (incident reporting, hazard/observation, inspections etc) and Compliance reporting (eg Audits, Regulator Engagement, IR)",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "Evan Darwen",
    "ProjectRole": "Health & Safety Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "06 - HSEQ",
    "Category": "HEALTH & SAFETY",
    "System": "UpVise",
    "Purpose": "Internal and External Plant Management system",
    "Requirement": "2 - Could Have",
    "Phase": "1- PAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "Evan Darwen",
    "ProjectRole": "Health & Safety Manager",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "07 - Stakeholder",
    "Category": "Comms / Engagement",
    "System": "Consultation Manager",
    "Purpose": "Centralised stakeholder relationship management platform.",
    "Requirement": "3 - Wont Have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Iain Billington",
    "ProjectRole": "IT Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "09 - Home Org",
    "Category": "BYOB",
    "System": "Device rental",
    "Purpose": "nan",
    "Requirement": "9 - Unknown",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "TBC",
    "ProjectRole": "TBC",
    "Adoption": "7 - Unknown",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "09 - Home Org",
    "Category": "BYOB",
    "System": "Home org associated costs ie SOE",
    "Purpose": "nan",
    "Requirement": "9 - Unknown",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "TBC",
    "ProjectRole": "TBC",
    "Adoption": "7 - Unknown",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "09 - Home Org",
    "Category": "BYOB",
    "System": "Accessories",
    "Purpose": "nan",
    "Requirement": "9 - Unknown",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "TBC",
    "ProjectRole": "TBC",
    "Adoption": "7 - Unknown",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "09 - Home Org",
    "Category": "HR Platforms",
    "System": "nan",
    "Purpose": "Internal home org platforms",
    "Requirement": "9 - Unknown",
    "Phase": "0 - IPAA",
    "Licence": "Zero Cost - BYOL",
    "SMEResponsible": "TBC",
    "ProjectRole": "TBC",
    "Adoption": "7 - Unknown",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "10 - Project Controls",
    "Category": "Information Management",
    "System": "MMS",
    "Purpose": "Documentation system",
    "Requirement": "0 - Must have",
    "Phase": "1- PAA",
    "Licence": "Cost - Pass Through",
    "SMEResponsible": "Evan Darwen",
    "ProjectRole": "Health & Safety Manager",
    "Adoption": "3 - good",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "10 - Project Controls",
    "Category": "Information Management",
    "System": "Aconex",
    "Purpose": "Document Management",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "AJ Loader",
    "ProjectRole": "IM Lead",
    "Adoption": "3 - good",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "10 - Project Controls",
    "Category": "Information Management",
    "System": "FlowForma",
    "Purpose": "Site-based electronic forms",
    "Requirement": "1 - Would Have",
    "Phase": "1- PAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "AJ Loader",
    "ProjectRole": "IM Lead",
    "Adoption": "8 - Not commenced",
    "HostedBy": "Third Party"
  },
  {
    "BusinessArea": "10 - Project Controls",
    "Category": "PROGRAMMING/SCHEDULING",
    "System": "Primavera P6",
    "Purpose": "Scheduling/programming (formal)",
    "Requirement": "0 - Must have",
    "Phase": "0 - IPAA",
    "Licence": "Unknown",
    "SMEResponsible": "Andy Goldie",
    "ProjectRole": "TBC",
    "Adoption": "4 - very good",
    "HostedBy": "Home Org"
  },
  {
    "BusinessArea": "10 - Project Controls",
    "Category": "Project Management",
    "System": "Jira + Confluence",
    "Purpose": "nan",
    "Requirement": "1 - Would Have",
    "Phase": "0 - IPAA",
    "Licence": "Cost - Procure",
    "SMEResponsible": "Dave Braendler",
    "ProjectRole": "DE Lead",
    "Adoption": "3 - good",
    "HostedBy": "Third Party"
  }
];