import { SystemInfo } from './types';

export const SYSTEMS_DATA: SystemInfo[] = [
  // Commercial Systems
  {
    id: 'candy-ccs',
    businessArea: '00 - Commercial',
    category: 'Estimating',
    name: 'Candy CCS',
    purpose: 'Estimating',
    requirement: '9 - Unknown',
    phase: '0 - IPAA',
    licenseType: 'Unknown',
    smeResponsible: 'TBC',
    projectRole: 'Commercial Manager',
    adoption: '8 - Not commenced',
    hostedBy: 'Third Party',
    icon: DollarSign
  },
  {
    id: 'my-hours',
    businessArea: '00 - Commercial',
    category: 'Financial',
    name: 'My Hours',
    purpose: 'Timesheet logging',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Cost - Procure',
    smeResponsible: 'Dave Braendler',
    projectRole: 'Digital Lead',
    adoption: '5 - comprehensive',
    hostedBy: 'Third Party',
    icon: Calendar
  },
  {
    id: 'workbench',
    businessArea: '00 - Commercial',
    category: 'Financial',
    name: 'Workbench & financial systems',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Cost - Procure',
    smeResponsible: 'Evan Darwen',
    projectRole: 'IT Lead',
    adoption: '3 - good',
    hostedBy: 'MacDow',
    icon: DollarSign
  },
  {
    id: 'sun-systems',
    businessArea: '00 - Commercial',
    category: 'Financial',
    name: 'Sun Systems',
    purpose: 'Accounting system for Payment of Suppliers, Balance Sheet and P&L Creation',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Cost - Pass Through',
    smeResponsible: 'Evan Darwen',
    projectRole: '',
    adoption: '8 - Not commenced',
    hostedBy: 'Third Party',
    icon: DollarSign
  },
  {
    id: 'project-orbit',
    businessArea: '00 - Commercial',
    category: 'Risk',
    name: 'Project Orbit',
    purpose: 'PowerBI tracking (Risk Tracking plus others)',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Cost - Procure',
    smeResponsible: 'Marcus Lin',
    projectRole: 'Risk Manager',
    adoption: '3 - good',
    hostedBy: 'T+T',
    icon: AlertTriangle
  },
  {
    id: 'arm',
    businessArea: '00 - Commercial',
    category: 'Risk',
    name: 'Actve Risk Manager (ARM)',
    purpose: 'Risk database',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - NZTA Provided',
    smeResponsible: 'Marcus Lin',
    projectRole: 'Risk Manager',
    adoption: '8 - Not commenced',
    hostedBy: 'NZTA',
    icon: AlertTriangle
  },

  {
    id: 'projectwise',
    businessArea: '01 - Design',
    category: '1 - Platform (CDE)',
    name: 'ProjectWise (Open Roads/Open Bridge)',
    purpose: 'OpenRoads - Roading and OpenBridge – Structures',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - Beca Provided',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '3 - good',
    hostedBy: 'Beca',
    icon: Database
  },
  {
    id: 'acc',
    businessArea: '01 - Design',
    category: '1 - Platform (CDE)',
    name: 'Autodesk Construction Cloud  (ACC)',
    purpose: 'Field data collection – quality assurance, quality control, internal audit',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - Beca Provided',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '2 - average',
    hostedBy: 'Beca',
    icon: Cloud
  },
  {
    id: 'seequent-central',
    businessArea: '01 - Design',
    category: '1 - Platform (CDE)',
    name: 'Seequent Central',
    purpose: '3D Modelling, Site Investigations',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Cost - Pass Through',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '3 - good',
    hostedBy: 'T+T',
    icon: Database
  },

  // Design Systems - Production
  {
    id: 'autocad',
    businessArea: '01 - Design',
    category: '2 - Production',
    name: 'Autocad',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '3 - good',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'open-roads',
    businessArea: '01 - Design',
    category: '2 - Production',
    name: 'Open Roads',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '5 - comprehensive',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'inventor',
    businessArea: '01 - Design',
    category: '2 - Production',
    name: 'Inventor',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Marcus Reiberg',
    projectRole: 'Temp Works/Construction',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'revit',
    businessArea: '01 - Design',
    category: '2 - Production',
    name: 'Revit',
    purpose: '',
    requirement: '2 - Could Have ',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke/Ted Polley',
    projectRole: 'CAD Lead/Structural Lead',
    adoption: '8 - Not commenced',
    hostedBy: 'Home Org',
    icon: Database
  },

  // Design Systems - Design Software
  {
    id: '12d-model',
    businessArea: '01 - Design',
    category: '3 - Design Software',
    name: '12D Model',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Wendy Cairns',
    projectRole: 'DE Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'open-roads-design',
    businessArea: '01 - Design',
    category: '3 - Design Software',
    name: 'Open Roads',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'open-bridge',
    businessArea: '01 - Design',
    category: '3 - Design Software',
    name: 'Open Bridge',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'civil-3d',
    businessArea: '01 - Design',
    category: '3 - Design Software',
    name: 'Civil 3D',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '7 - Unknown',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'leap-frog',
    businessArea: '01 - Design',
    category: '3 - Design Software',
    name: 'Leap Frog',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'csi-bridge',
    businessArea: '01 - Design',
    category: '3 - Design Software',
    name: 'CSi Bridge',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '7 - Unknown',
    hostedBy: 'Home Org',
    icon: Database
  },
  {
    id: 'space-grass',
    businessArea: '01 - Design',
    category: '3 - Design Software',
    name: 'Space Grass',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'DE Lead',
    adoption: '7 - Unknown',
    hostedBy: 'Home Org',
    icon: Database
  },

  // Design Systems - Federation
  {
    id: 'itwin',
    businessArea: '01 - Design',
    category: '4 - Federation',
    name: 'iTwin',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - Beca Provided',
    smeResponsible: 'Matt Arcus',
    projectRole: 'Geeometrics Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Monitor
  },
  {
    id: 'bluebeam',
    businessArea: '01 - Design',
    category: '4 - Federation',
    name: 'BlueBeam',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '3 - good',
    hostedBy: 'Home Org',
    icon: FileText
  },
  {
    id: 'navisworks',
    businessArea: '01 - Design',
    category: '4 - Federation',
    name: 'Navisworks',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '8 - Not commenced',
    hostedBy: 'Home Org',
    icon: Monitor
  },

  // Design Systems - Visualization
  {
    id: 'lumenrt',
    businessArea: '01 - Design',
    category: '5 - Visualization',
    name: 'LumenRT',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - Beca Provided',
    smeResponsible: 'Craig Burke',
    projectRole: 'CAD Lead',
    adoption: '8 - Not commenced',
    hostedBy: 'Home Org',
    icon: Monitor
  },

  // Design Systems - Geotechnical
  {
    id: 'plaxis-2d',
    businessArea: '01 - Design',
    category: '6 - Geotechnical',
    name: 'PLAXIS 2D',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Monitor
  },
  {
    id: 'slope-w',
    businessArea: '01 - Design',
    category: '6 - Geotechnical',
    name: 'SLOPE/W',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Monitor
  },
  {
    id: 'slide2',
    businessArea: '01 - Design',
    category: '6 - Geotechnical',
    name: 'Slide2',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Monitor
  },
  {
    id: 'wallap',
    businessArea: '01 - Design',
    category: '6 - Geotechnical',
    name: 'WALLAP',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Monitor
  },
  {
    id: 'settle3',
    businessArea: '01 - Design',
    category: '6 - Geotechnical',
    name: 'Settle3',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Monitor
  },
  {
    id: 'msew-plus',
    businessArea: '01 - Design',
    category: '6 - Geotechnical',
    name: 'MSEW+',
    purpose: '',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Zero Cost - BYOL',
    smeResponsible: 'Emma Christie',
    projectRole: 'Geotech Lead',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Monitor
  }, 
  // IT Systems
  {
    id: 'sharepoint',
    businessArea: '03 - IT',
    category: 'NZTA Provided',
    name: 'Sharepoint Hub, Infrastructure, Networking, Security, etc',
    purpose: '',
    requirement: '0 - Must have',
    phase: '1- PAA',
    licenseType: 'Zero Cost - NZTA Provided',
    smeResponsible: 'Iain Billington',
    projectRole: 'IT Lead',
    adoption: '3 - good',
    hostedBy: 'Third Party',
    icon: Cloud
  },
  {
    id: 'south-sharepoint',
    businessArea: '03 - IT',
    category: 'Base IT Services',
    name: 'South - Sharepoint + Services',
    purpose: 'Refer tab "3-IT"',
    requirement: '0 - Must have',
    phase: '2 - IPAA + PAA',
    licenseType: 'Cost - Procure',
    smeResponsible: 'Iain Billington',
    projectRole: 'IT Lead',
    adoption: '8 - Not commenced',
    hostedBy: 'Third Party',
    icon: Cloud
  },
  {
    id: 'south-internet',
    businessArea: '03 - IT',
    category: 'Base IT Services',
    name: 'South - Internet + Security',
    purpose: 'Refer tab "3-IT"',
    requirement: '0 - Must have',
    phase: '2 - IPAA + PAA',
    licenseType: 'Cost - Procure',
    smeResponsible: 'Iain Billington',
    projectRole: 'IT Lead',
    adoption: '9 - N/A',
    hostedBy: 'Third Party',
    icon: Network
  },
  {
    id: 'south-storage',
    businessArea: '03 - IT',
    category: 'Base IT Services',
    name: 'South - Data Storage',
    purpose: 'Refer tab "3-IT"',
    requirement: '0 - Must have',
    phase: '2 - IPAA + PAA',
    licenseType: 'Cost - Procure',
    smeResponsible: 'Iain Billington',
    projectRole: 'IT Lead',
    adoption: '8 - Not commenced',
    hostedBy: 'Third Party',
    icon: Database
  },

  // Project Controls Systems
  {
    id: 'mms',
    businessArea: '10 - Project Controls',
    category: 'Information Management',
    name: 'MMS',
    purpose: 'Documentation system',
    requirement: '0 - Must have',
    phase: '1- PAA',
    licenseType: 'Cost - Pass Through',
    smeResponsible: 'Evan Darwen',
    projectRole: 'Health & Safety Manager',
    adoption: '3 - good',
    hostedBy: 'Third Party',
    icon: FileText
  },
  {
    id: 'aconex',
    businessArea: '10 - Project Controls',
    category: 'Information Management',
    name: 'Aconex',
    purpose: 'Document Management',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Cost - Procure',
    smeResponsible: 'AJ Loader',
    projectRole: 'IM Lead',
    adoption: '3 - good',
    hostedBy: 'Third Party',
    icon: FileText
  },
  {
    id: 'primavera',
    businessArea: '10 - Project Controls',
    category: 'PROGRAMMING/SCHEDULING',
    name: 'Primavera P6',
    purpose: 'Scheduling/programming (formal)',
    requirement: '0 - Must have',
    phase: '0 - IPAA',
    licenseType: 'Unknown',
    smeResponsible: 'Andy Goldie',
    projectRole: 'TBC',
    adoption: '4 - very good',
    hostedBy: 'Home Org',
    icon: Calendar
  }
];

// Helper function to get status based on adoption level
export const getSystemStatus = (adoption: Adoption): SystemStatus => {
  switch (adoption) {
    case '4 - very good':
    case '5 - comprehensive':
    case '3 - good':
      return 'operational';
    case '2 - average':
      return 'degraded';
    case '1 - poor':
      return 'maintenance';
    case '8 - Not commenced':
      return 'not-started';
    default:
      return 'outage';
  }
};



